# Prometheus配置文件
# 用于监控WebSocket客户端的性能指标

global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'websocket-client-monitor'

# 规则文件
rule_files:
  - "alert_rules.yml"

# 告警管理器配置
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

# 抓取配置
scrape_configs:
  # Prometheus自身监控
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    scrape_interval: 5s
    metrics_path: /metrics

  # WebSocket客户端监控
  - job_name: 'websocket-client'
    static_configs:
      - targets: ['websocket-client:9090']
    scrape_interval: 5s
    metrics_path: /metrics
    scrape_timeout: 10s
    honor_labels: true
    params:
      format: ['prometheus']

  # 负载测试监控
  - job_name: 'load-tester'
    static_configs:
      - targets: ['load-tester:9092']
    scrape_interval: 10s
    metrics_path: /metrics
    scrape_timeout: 5s

  # 系统监控（如果有node_exporter）
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 15s
    metrics_path: /metrics

  # Docker容器监控（如果有cadvisor）
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
    scrape_interval: 15s
    metrics_path: /metrics

  # Redis监控（如果有redis_exporter）
  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']
    scrape_interval: 15s
    metrics_path: /metrics

# 远程写入配置（可选）
# remote_write:
#   - url: "https://prometheus-remote-write-endpoint"
#     basic_auth:
#       username: "user"
#       password: "password"

# 远程读取配置（可选）
# remote_read:
#   - url: "https://prometheus-remote-read-endpoint"
#     basic_auth:
#       username: "user"
#       password: "password"
